[package]
name = "mp4ff-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "mp4ff"

[dependencies]

[features]
default = []
openh264 = []

[[example]]
name = "thumbnail"
path = "examples/thumbnail.rs"
required-features = ["openh264"]
